### ISSUE TITLE
Parsing failed, no decoding mapping for 254 with pcapng file

### ISSUE THREAD

**Issue by ifohancroft** [Flameeyes/usbmon-tools#3]
After cloning the repo and running `sudo python setup.py build` and `sudo python setup.py install` then running `usbmon-chatter_hid --address-prefix 1.12.0 /path/to/file.pcapng` I get the follow error:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/construct-2.10.67-py3.9.egg/construct/core.py", line 2019, in _decode
KeyError: 254

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/usbmon-chatter_hid", line 33, in <module>
    sys.exit(load_entry_point('usbmon-tools==3.dev15+gc655797', 'console_scripts', 'usbmon-chatter_hid')())
  File "/usr/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/usbmon_tools-3.dev15+gc655797-py3.9.egg/usbmon/tools/chatter_hid.py", line 56, in main
  File "/usr/lib/python3.9/site-packages/usbmon_tools-3.dev15+gc655797-py3.9.egg/usbmon/pcapng.py", line 96, in parse_stream
  File "/usr/lib/python3.9/site-packages/usbmon_tools-3.dev15+gc655797-py3.9.egg/usbmon/capture/usbpcap.py", line 74, in __init__
  File "/usr/lib/python3.9/site-packages/construct-2.10.67-py3.9.egg/construct/core.py", line 288, in parse
  File "/usr/lib/python3.9/site-packages/construct-2.10.67-py3.9.egg/construct/core.py", line 300, in parse_stream
  File "/usr/lib/python3.9/site-packages/construct-2.10.67-py3.9.egg/construct/core.py", line 312, in _parsereport
  File "/usr/lib/python3.9/site-packages/construct-2.10.67-py3.9.egg/construct/core.py", line 2120, in _parse
  File "/usr/lib/python3.9/site-packages/construct-2.10.67-py3.9.egg/construct/core.py", line 312, in _parsereport
  File "/usr/lib/python3.9/site-packages/construct-2.10.67-py3.9.egg/construct/core.py", line 2653, in _parse
  File "/usr/lib/python3.9/site-packages/construct-2.10.67-py3.9.egg/construct/core.py", line 312, in _parsereport
  File "/usr/lib/python3.9/site-packages/construct-2.10.67-py3.9.egg/construct/core.py", line 704, in _parse
  File "/usr/lib/python3.9/site-packages/construct-2.10.67-py3.9.egg/construct/core.py", line 2021, in _decode
construct.core.MappingError: Error in path (parsing) -> xfer_type
parsing failed, no decoding mapping for 254

**Comment by ifohancroft** [comment]
The same thing happens if I don't install the package but instead run it using `python /path/to/usbmon-tools/usbmon/tools/chatter_hid.py --address-prefix 1.12.0 /path/to/file.pcapng`

**Comment by Flameeyes** [comment]
Hah, this is due to https://github.com/desowin/usbpcap/commit/897c60507b46608e86cf077a1f3163c074bdee70 which appears to not have been documented. I'll have a quick fix probably in a moment.

**Comment by Flameeyes** [comment]
(The harder part is getting a capture to test this, hopefully my last HyperV VM can still run.)

**Comment by ifohancroft** [comment]
Yeah, it seems there hasn't been much work done on usbpcap lately. I have made a bug report there recently about some unrecognized URB Function Codes and there haven't been any activity.

P.S. I PM'd you a capture URL on IRC.
