### ISSUE TITLE
AssertionError from chatter_cp*

### ISSUE THREAD

**Issue by ifohancroft** [Flameeyes/usbmon-tools#4]
Executing either chatter_cp, providing a device address and a file, I get this:

```Traceback (most recent call last):
  File "/usr/bin/usbmon-chatter_cp210x", line 33, in <module>
    sys.exit(load_entry_point('usbmon-tools==3.dev17+g4e27bb1', 'console_scripts', 'usbmon-chatter_cp210x')())
  File "/usr/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/usbmon_tools-3.dev17+g4e27bb1-py3.9.egg/usbmon/tools/chatter_cp210x.py", line 123, in main
AssertionError
```

**Comment by Flameeyes** [comment]
This should now erroring out more clearly stating that the capture is not of the right device (hopefully).
